# Define el archivo Docker a usar
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Clone repository
    command: |
      # Clonar el repositorio de GitHub
      git clone https://github.com/faustinoloeza/currencyapp /workspace/currencyapp
      cd /workspace/currencyapp

  - name: Run project
    command: |
      # Limpiar la terminal
      printf "\033[3J\033c\033[3J" 
      # Ejecutar JetBrains Toolbox
      cd /opt/jetbrains-toolbox
      ./jetbrains-toolbox
      

# Definir cómo manejar diferentes puertos
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore
