# Define the Docker image to use
image:
  file: .gitpod.Dockerfile

# Define how to handle different ports
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore

# Define VS Code extensions to install
vscode:
  extensions:
    - dart-code.flutter
