# Define el archivo Docker a usar
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Clone repository
    command: |
      # Clonar el repositorio de GitHub
      git clone https://github.com/faustinoloeza/currencyapp /workspace/currencyapp
      cd /workspace/currencyapp

  - name: Run project
    command: |
      # Limpiar la terminal
      printf "\033[3J\033c\033[3J" 
      # Ejecutar JetBrains Toolbox
      cd /opt/jetbrains-toolbox
      ./jetbrains-toolbox
      
  - name: Install JetBrains Fleet
    command: |
      sleep 30 # Espera a que JetBrains Toolbox se inicie completamente
      TOOLBOX_API_PORT=$(lsof -i -P -n | grep jetbrains-toolb | grep LISTEN | awk '{print $9}' | cut -d: -f2)
      TOOLBOX_API_URL="http://localhost:$TOOLBOX_API_PORT/api/v1"
      PRODUCT_CODE="fleet"
      curl -X POST "$TOOLBOX_API_URL/install?code=$PRODUCT_CODE"
# Definir cómo manejar diferentes puertos
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore
